
Abrindo o banco de dados e criando o dataframe

```{r}
# The easiest way to get ggplot2 is to install the whole tidyverse:
#install.packages("tidyverse")

# Alternatively, install just ggplot2:
#install.packages("ggplot2")
#install.packages("patchwork")
# Carregue o pacote gridExtra (caso ainda não tenha feito)

library(gridExtra)
library(zoo)
library(ggplot2)
library(reshape2)
library(readxl)
library(RColorBrewer)
library(dplyr)
setwd("C:/Banco_de_Dados")
dados <- read_xlsx("TRATAMENTO_CPTU_TODOS.xlsx",sheet = "DADOS DE ENTRADA - CPTU",range = "B43:CH13022")

```


```{r}

dados_SCPTU_P4 <- dados %>% filter(FURO == "SCPTu-P4")

sumario_dados_profundidade <- summary(dados_SCPTU_P4$`PROF. (m)`)
sumario_dados_resistencia <- summary(dados_SCPTU_P4$`qc (MPa)`)
IQR_qc <- IQR(dados_SCPTU_P4$`qc (MPa)`)

Lower_resistencia <- sumario_dados_resistencia[2] - 1.5 * IQR_qc
Upper_resistencia <- sumario_dados_resistencia[5] + 1.5 * IQR_qc
Min_profundidade <- sumario_dados_profundidade[1]
Max_profundidade <- sumario_dados_profundidade[6]


# Filtra os valores outliers
Resitencia_de_ponta_filtrado_SCPTU_P4 <- dados_SCPTU_P4 %>% 
  filter(`qc (MPa)` >= Lower_resistencia & `qc (MPa)` <= Upper_resistencia)

```


```{r}
heatmap_qc_filtrado_SCPTU_P4 <- ggplot(data = Resitencia_de_ponta_filtrado_SCPTU_P4, aes(x = `qc (MPa)`, y = `PROF. (m)`)) +
  stat_density_2d(aes(fill = after_stat(density)), geom = "raster", contour = FALSE, interpolate = TRUE, alpha = 0.8) +
  scale_fill_gradientn(colours = c("#034e7b", "#1c86c6", "#a6bddb", "#fdae61", "#d7191c"), name = "Densidade", guide = "none") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_reverse(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, 2.25), ylim = c(Max_profundidade, Min_profundidade)) +
  theme(legend.position = "right",
        plot.title = element_text(hjust = 0.5, margin = margin(b = 10)),
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10)),
        plot.margin = margin(t = 30, r = 30, b = 30, l = 30)) +
  labs(x = "qc (MPa)",
       y = "Profundidade (m)") +
  geom_smooth(method = "lm", formula = y ~ poly(x, 1), se = FALSE, color = "#3D2B1F", linewidth = 1, linetype = "solid", alpha = 0.5)

heatmap_qc_filtrado_SCPTU_P4

ggsave(filename = "imagens/heatmap_qc_filtrado_SCPTU_P4.png", plot = heatmap_qc_filtrado_SCPTU_P4, width = 8, height = 6, units = "in")


```


```{r}
dados_CPTu_02 <- dados %>% filter(FURO == "CPTu-02")

sumario_dados_profundidade <- summary(dados_CPTu_02$`PROF. (m)`)
sumario_dados_resistencia <- summary(dados_CPTu_02$`qc (MPa)`)
IQR_qc <- IQR(dados_CPTu_02$`qc (MPa)`)

Lower_resistencia <- sumario_dados_resistencia[2] - 1.5 * IQR_qc
Upper_resistencia <- sumario_dados_resistencia[5] + 1.5 * IQR_qc
Min_profundidade <- sumario_dados_profundidade[1]
Max_profundidade <- sumario_dados_profundidade[6]


# Filtra os valores outliers
Resitencia_de_ponta_filtrado_CPTu_02 <- dados_CPTu_02 %>% 
  filter(`qc (MPa)` >= Lower_resistencia & `qc (MPa)` <= Upper_resistencia)

```

```{r}
ggplot(data = Resitencia_de_ponta_filtrado_CPTu_02, aes(x = `qc (MPa)`, y = `PROF. (m)`)) +
  stat_density_2d(aes(fill = after_stat(density)), geom = "raster", contour = FALSE, interpolate = TRUE, alpha = 0.8) +
  scale_fill_gradientn(colours = c("#034e7b", "#1c86c6", "#a6bddb", "#fdae61", "#d7191c"), name = "Densidade", guide = "none") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_reverse(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0.1, Upper_resistencia), ylim = c(Max_profundidade, Min_profundidade)) +
  theme(legend.position = "right",
        plot.title = element_text(hjust = 0.5, margin = margin(b = 10)),
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10)),
        plot.margin = margin(t = 30, r = 30, b = 30, l = 30)) +
  labs(x = "qc (MPa)",y = "Profundidade (m)") +
  ggtitle("CPTu-02") +
  geom_smooth(method = "lm", formula = y ~ poly(x, 1), se = FALSE, color = "#3D2B1F", linewidth = 1, linetype = "solid", alpha = 0.5)

ggsave(filename = "imagens/heatmap_qc_filtrado_CPTu_02.png", plot = last_plot(), width = 8, height = 6, units = "in")

```

```{r}

dados_CPTu_02a <- dados %>% filter(FURO == "CPTu-02a")

sumario_dados_profundidade <- summary(dados_CPTu_02a$`PROF. (m)`)
sumario_dados_resistencia <- summary(dados_CPTu_02a$`qc (MPa)`)
IQR_qc <- IQR(dados_CPTu_02a$`qc (MPa)`)

Lower_resistencia <- sumario_dados_resistencia[2] - 1.5 * IQR_qc
Upper_resistencia <- sumario_dados_resistencia[5] + 1.5 * IQR_qc
Min_profundidade <- sumario_dados_profundidade[1]
Max_profundidade <- sumario_dados_profundidade[6]


# Filtra os valores outliers
Resitencia_de_ponta_filtrado_CPTu_02a <- dados_CPTu_02a %>% 
  filter(`qc (MPa)` >= Lower_resistencia & `qc (MPa)` <= Upper_resistencia)

```

```{r}

ggplot(data = Resitencia_de_ponta_filtrado_CPTu_02a, aes(x = `qc (MPa)`, y = `PROF. (m)`)) +
  stat_density_2d(aes(fill = after_stat(density)), geom = "raster", contour = FALSE, interpolate = TRUE, alpha = 0.8) +
  scale_fill_gradientn(colours = c("#034e7b", "#1c86c6", "#a6bddb", "#fdae61", "#d7191c"), name = "Densidade", guide = "none") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_reverse(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0.05, Upper_resistencia), ylim = c(Max_profundidade, Min_profundidade)) +
  theme(legend.position = "right",
        plot.title = element_text(hjust = 0.5, margin = margin(b = 10)),
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10)),
        plot.margin = margin(t = 30, r = 30, b = 30, l = 30)) +
  labs(title = "Heatmap de Frequência de Resistência de Ponta",
       x = "qc (MPa)",
       y = "Profundidade (m)") +
  ggtitle("CPTu-02a") +
  geom_smooth(method = "lm", formula = y ~ poly(x, 1), se = FALSE, color = "#3D2B1F", linewidth = 1, linetype = "solid", alpha = 0.5)

ggsave(filename = "imagens/heatmap_qc_filtrado_CPTu_02a.png", plot = last_plot(), width = 8, height = 6, units = "in")



```
```{r}
dados_SCPTu_01 <- dados %>% filter(FURO == "SCPTu-01")

sumario_dados_profundidade <- summary(dados_SCPTu_01$`PROF. (m)`)
sumario_dados_resistencia <- summary(dados_SCPTu_01$`qc (MPa)`)
IQR_qc <- IQR(dados_SCPTu_01$`qc (MPa)`)

Lower_resistencia <- sumario_dados_resistencia[2] - 1.5 * IQR_qc
Upper_resistencia <- sumario_dados_resistencia[5] + 1.5 * IQR_qc
Min_profundidade <- sumario_dados_profundidade[1]
Max_profundidade <- sumario_dados_profundidade[6]


# Filtra os valores outliers
Resitencia_de_ponta_filtrado_SCPTu_01 <- dados_SCPTu_01 %>% 
  filter(`qc (MPa)` >= Lower_resistencia & `qc (MPa)` <= Upper_resistencia)

```

```{r}
ggplot(data = Resitencia_de_ponta_filtrado_SCPTu_01, aes(x = `qc (MPa)`, y = `PROF. (m)`)) +
  stat_density_2d(aes(fill = after_stat(density)), geom = "raster", contour = FALSE, interpolate = TRUE, alpha = 0.8) +
  scale_fill_gradientn(colours = c("#034e7b", "#1c86c6", "#a6bddb", "#fdae61", "#d7191c"), name = "Densidade", guide = "none") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_reverse(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0.3, 1.3), ylim = c(Max_profundidade, 12.31)) +
  theme(legend.position = "right",
        plot.title = element_text(hjust = 0.5, margin = margin(b = 10)),
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10)),
        plot.margin = margin(t = 30, r = 30, b = 30, l = 30)) +
  labs(title = "Heatmap de Frequência de Resistência de Ponta",
       x = "qc (MPa)",
       y = "Profundidade (m)") +
  ggtitle("SCPTu-01") +
  geom_smooth(method = "lm", formula = y ~ poly(x, 1), se = FALSE, color = "#3D2B1F", linewidth = 1, linetype = "solid", alpha = 0.5)

ggsave(filename = "imagens/heatmap_qc_filtrado_SCPTu_01.png", plot = last_plot(), width = 8, height = 6, units = "in")
```
```{r}
dados_SCPTu_02 <- dados %>% filter(FURO == "SCPTu-02")

sumario_dados_profundidade <- summary(dados_SCPTu_02$`PROF. (m)`)
sumario_dados_resistencia <- summary(dados_SCPTu_02$`qc (MPa)`)
IQR_qc <- IQR(dados_SCPTu_02$`qc (MPa)`)

Lower_resistencia <- sumario_dados_resistencia[2] - 1.5 * IQR_qc
Upper_resistencia <- sumario_dados_resistencia[5] + 1.5 * IQR_qc
Min_profundidade <- sumario_dados_profundidade[1]
Max_profundidade <- sumario_dados_profundidade[6]

# Filtra os valores outliers
Resitencia_de_ponta_filtrado_SCPTu_02 <- dados_SCPTu_02 %>% 
  filter(`qc (MPa)` >= Lower_resistencia & `qc (MPa)` <= Upper_resistencia)
```

```{r}
ggplot(data = Resitencia_de_ponta_filtrado_SCPTu_02, aes(x = `qc (MPa)`, y = `PROF. (m)`)) +
  stat_density_2d(aes(fill = after_stat(density)), geom = "raster", contour = FALSE, interpolate = TRUE, alpha = 0.8) +
  scale_fill_gradientn(colours = c("#034e7b", "#1c86c6", "#a6bddb", "#fdae61", "#d7191c"), name = "Densidade", guide = "none") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_reverse(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0.1, 1.6), ylim = c(Max_profundidade, Min_profundidade)) +
  theme(legend.position = "right",
        plot.title = element_text(hjust = 0.5, margin = margin(b = 10)),
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10)),
        plot.margin = margin(t = 30, r = 30, b = 30, l = 30)) +
  labs(x = "qc (MPa)",y = "Profundidade (m)") +
  ggtitle("SCPTu-02") +
  geom_smooth(method = "lm", formula = y ~ poly(x, 1), se = FALSE, color = "#3D2B1F", linewidth = 1, linetype = "solid", alpha = 0.5)

ggsave(filename = "imagens/heatmap_qc_filtrado_SCPTu_02.png", plot = last_plot(), width = 8, height = 6, units = "in")

```

```{r}
dados_SCPTu_14 <- dados %>% filter(FURO == "SCPTu-14")

sumario_dados_profundidade <- summary(dados_SCPTu_14$`PROF. (m)`)
sumario_dados_resistencia <- summary(dados_SCPTu_14$`qc (MPa)`)
IQR_qc <- IQR(dados_SCPTu_14$`qc (MPa)`)

Lower_resistencia <- sumario_dados_resistencia[2] - 1.5 * IQR_qc
Upper_resistencia <- sumario_dados_resistencia[5] + 1.5 * IQR_qc
Min_profundidade <- sumario_dados_profundidade[1]
Max_profundidade <- sumario_dados_profundidade[6]

# Filtra os valores outliers
Resitencia_de_ponta_filtrado_SCPTu_14 <- dados_SCPTu_14 %>% 
  filter(`qc (MPa)` >= Lower_resistencia & `qc (MPa)` <= Upper_resistencia)
```

```{r}
ggplot(data = Resitencia_de_ponta_filtrado_SCPTu_14, aes(x = `qc (MPa)`, y = `PROF. (m)`)) +
  stat_density_2d(aes(fill = after_stat(density)), geom = "raster", contour = FALSE, interpolate = TRUE, alpha = 0.8) +
  scale_fill_gradientn(colours = c("#034e7b", "#1c86c6", "#a6bddb", "#fdae61", "#d7191c"), name = "Densidade", guide = "none") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_reverse(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, Upper_resistencia), ylim = c(Max_profundidade, Min_profundidade)) +
  theme(legend.position = "right",
        plot.title = element_text(hjust = 0.5, margin = margin(b = 10)),
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10)),
        plot.margin = margin(t = 30, r = 30, b = 30, l = 30)) +
  labs(x = "qc (MPa)",y = "Profundidade (m)") +
  ggtitle("SCPTu-14") +
  geom_smooth(method = "lm", formula = y ~ poly(x, 1), se = FALSE, color = "#3D2B1F", linewidth = 1, linetype = "solid", alpha = 0.5)

ggsave(filename = "imagens/heatmap_qc_filtrado_SCPTu_14.png", plot = last_plot(), width = 8, height = 6, units = "in")
```

